name: CI

on:
  push:
    branches:
      - main


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Venv Enviroment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencias
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run static code analysis with flake 8
        run: |
          source venv/bin/activate 
          flake8 my_app/my_app_v2.py

      - name: Run static code analysis with mypy
        run: |
          source venv/bin/activate 
          mypy my_app --configfile mypy.ini